# -*- coding: utf-8 -*-
"""LLM-HF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyVm9MfSnHlHQ8AWj7PMzyQfnRymYJ_I
"""

from transformers import BertConfig, BertModel
bert_config = BertConfig.from_pretrained("bert-base-cased")
bert_model = BertModel(bert_config)

#Saving model
bert_model.save_pretrained("my-bert-model")

#Reloading the saved model
Bert_Model = BertModel.from_pretrained("my-bert-model")

#Creating a Transformer

from transformers import AutoModel
model = AutoModel.from_pretrained("bert-base-cased")

#Saving this model

model.save_pretrained("directory_on_my_computer")

from huggingface_hub import notebook_login
notebook_login()

model.push_to_hub("my-basic-model-demo")

from transformers import AutoTokenizer
from pprint import pprint

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

encoded_input = tokenizer("Hello, this is the first practice file of HF transformers.")

pprint(encoded_input)

tokenizer.decode(encoded_input["input_ids"])

#Padding inputs
encoded_input = tokenizer(
    ["How are you?", "I'm fine, thank you!"], padding=True, return_tensors="pt"
)
print(encoded_input)

#Truncating inputs
encoded_input = tokenizer(
    "This is a very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long sentence.",
    truncation=True,
)
print(encoded_input["input_ids"])

encoded_input = tokenizer(
    ["How are you?", "I'm fine, thank you!"],
    padding=True,
    truncation=True,
    max_length=5,
    return_tensors="pt",
)
print(encoded_input)

#Example:
sequences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

encoded_sequences = [
    [
        101,
        1045,
        1005,
        2310,
        2042,
        3403,
        2005,
        1037,
        17662,
        12172,
        2607,
        2026,
        2878,
        2166,
        1012,
        102,
    ],
    [101, 1045, 5223, 2023, 2061, 2172, 999, 102],
]

import torch

# The sequences variable is available from previous cells
# We will re-encode them with padding and return them as PyTorch tensors
model_inputs = tokenizer(sequences, padding=True, return_tensors="pt")

output = model(**model_inputs)

print(output)

#use a pipeline as a high-lvl helper
from transformers import pipeline
pipe = pipeline("question-answering")

pipe(
    question ="What is the capital of India?",
    context ="The capital of India is New Delhi.",
)

from transformers import pipeline
pipe = pipeline("text-generation", model="bert-base-cased", max_length=10)
txt = "You are a model that does "
result = pipe(txt)

print(result[0]["generated_text"])

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")

name = "unbelievable"
input = tokenizer(name, return_tensors="pt").input_ids
input

print(tokenizer.decode(input))

for token_id in input.squeeze():
  print(tokenizer.decode(token_id))

"""##AutoModelCausalLM"""

from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("gpt2")

model

"""Data Processing Technique"""

sentence = "I like machine learning to be able to"

token_ids = tokenizer(sentence, return_tensors="pt").input_ids

outputs = model(token_ids).logits[0, -1]
tokenizer.decode(outputs.argmax())

sentence ="I am learning a lot from"

token_ids = tokenizer(sentence, return_tensors="pt").input_ids
outputs = model(token_ids).logits[0, -1]

final_logits = torch.topk(outputs, 5)
final_logits

for index in final_logits.indices:
  print(tokenizer.decode(index))

# tokenizer.decode(final_logits.indices.tolist())

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import torch.nn.functional as F

model_name = "gpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

sentence = "I am learning"

inputs = tokenizer(sentence, return_tensors="pt")

output = model.generate(
    **inputs,
    max_length=20,
    num_return_sequences=1,
    do_sample=True,
    temperature=0.7
)

result = tokenizer.decode(output[0], skip_special_tokens=True)
print(result)

torch.softmax(final_logits.values, dim=0).sum()

def greedy_decode(logits):
  """Return token index with maximum probability."""
  return torch.argmax(logits, dim=-1)

def top_k_sampling(logits, k=50):
  """
  Keeps only top-k logits, normalize them into probability.
  then sample one token from the filtered distribution.
  """

  values, indices = torch.topk(logits, k)
  probs = F.softmax(values, dim=-1)
  sampled = torch.multinomial(probs, 1)
  return indices[sampled]

def top_p_sampling(logits, p=0.9):
    """
    Sort tokens by probability, keep smallest number whose cumulative probability
    exceeds threshold p, then sample one token.
    """

    sorted_logits, sorted_indices = torch.sort(logits, descending=True)
    sorted_probs = F.softmax(sorted_logits, dim=-1)
    cumulative_probs = sorted_probs.cumsum(dim=-1)

    #Mask token outside nucleus
    mask = cumulative_probs > p
    sorted_logits[mask] = float("-inf")

    #Sample from filtered logits
    filtered_probs = F.softmax(sorted_logits, dim=-1)
    sampled = torch.multinomial(filtered_probs, 1)

    #Return token index in original vocabulary
    return sorted_indices[sampled]

#Temperature Sampling

def temperature_sampling(logits, temperature=1.0):
    """
    Scale logits by temperature before sampling.
    Lower temperature => sharper distribution
    """

    scaled = logits / temperature
    probs = F.softmax(scaled, dim=-1)
    return torch.multinomial(probs, 1)

#Random sampling
def random_sampling(logits):
    """
    Sample directly from softmax distribution without filtering
    """
    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)

sentence = "Today I decided to go to the local"
inputs = tokenizer(sentence, return_tensors="pt")
output = model(**inputs)
logits = output.logits[0, -1]

print(f"Greedy Decode: ", tokenizer.decode(greedy_decode(logits)))
print(f"Top-k Sampling: ", tokenizer.decode(top_k_sampling(logits, k=5)))
print(f"Top-p Sampling: ", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print(f"Temperature Sampling: ", tokenizer.decode(temperature_sampling(logits, temperature=0.7)))
print(f"Random Sampling: ", tokenizer.decode(random_sampling(logits)))

top_k_sampling(outputs)

tokenizer.decode(top_k_sampling(outputs))

outputs

top_p_sampling(outputs, p=0.9)
tokenizer.decode(top_p_sampling(outputs, p=0.9))

tokenizer.decode(temperature_sampling(outputs, temperature=1.0))

tokenizer.decode(random_sampling(outputs))

import torch
import torch.nn.functional as F

sentence = "I learn Machine learning to enhance my work. I learn how"
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
logits = model(token_ids).logits # Raw unnormalized score - values

# Get the logits for the last token in the sequence
last_token_logits = logits[0, -1]

# Apply softmax to get probabilities
probabilities = F.softmax(last_token_logits, dim=-1)

# Now, apply torch.topk to these probabilities
top5 = torch.topk(probabilities, k=5)

for index, value in zip(top5.indices, top5.values):
  print(f"{tokenizer.decode(index)} -- {value:.1%}")

